version: '3'

services:

  moodle:
    container_name: moodle_$URL_DEPLOY
    image: iesgn/moodle_aulavirtual:$VERSION_DEPLOY
    volumes:
      - '/srv/moodledata_aulavirtual:/var/www/moodledata:rw'
    ports:
      - '$PORT_DEPLOY:80'
    extra_hosts:
      - "sql.gonzalonazareno.org:172.18.0.1"
      - "correo.gonzalonazareno.org:172.18.0.1"
    environment:
      MOODLE_DBNAME: ${DB_NAME}
      MOODLE_DBUSER: ${DB_USER}
      MOODLE_DBPASS: ${DB_PASSWORD}
      MOODLE_DBHOST: sql.gonzalonazareno.org
      # development
      #MOODLE_WWWROOT: http://$URL_DEPLOY:$PORT_DEPLOY
      # production
      MOODLE_WWWROOT: https://$URL_DEPLOY


    restart: always
